if (typeof firebase === "undefined") {
  document.getElementById("authError").innerText = "Could not load Firebase. Check internet and refresh.";
}

const firebaseConfig = {
  apiKey: "AIzaSyDcHQYy1jYQE5C2czUyd_Dfwas7W_YadsA",
  authDomain: "story-keeper-69461.firebaseapp.com",
  projectId: "story-keeper-69461",
  storageBucket: "story-keeper-69461.firebasestorage.app",
  messagingSenderId: "98973797111",
  appId: "1:98973797111:web:902a992029baf15f5a61f2",
  measurementId: "G-7HGDZ7SRHQ"
};
const GM_EMAIL = "priestessriel@storykeeper.game";

firebase.initializeApp(firebaseConfig);
const auth = firebase.auth();
const db = firebase.firestore();

function isGM() { return currentUser && currentUser.email && currentUser.email.toLowerCase() === GM_EMAIL.toLowerCase(); }
function updateGMVisibility() { const b = document.getElementById("tab-btn-desk"); if (b) b.style.display = isGM() ? "" : "none"; if (!isGM() && currentTab === "desk") showTab("inscribe"); }

function showTab(t) { if (t === "desk" && !isGM()) t = "inscribe"; currentTab = t; const p = ["inscribe","team","reading","companions","archive","desk"]; for (const x of p) { document.getElementById("tab-" + x).style.display = x === t ? "block" : "none"; const b = document.getElementById("tab-btn-" + x); if (x === t) b.classList.add("active"); else b.classList.remove("active"); } }

function saveState() {
  if (!state) return;
  try { localStorage.setItem("storykeeper_save_local", JSON.stringify(state)); } catch (e) {}
  if (auth.currentUser) { db.collection("players").doc(auth.currentUser.uid).set(state).catch(function (e) { console.error(e); }); }
}

function loadUserData(user) {
  db.collection("players").doc(user.uid).get().then(function (snap) {
    if (snap.exists) { state = snap.data(); ensureCollections(); } else { state = defaultState(); saveState(); }
    document.getElementById("loginScreen").style.display = "none";
    document.getElementById("gameApp").style.display = "block";
    document.getElementById("userEmail").innerText = user.email;
    renderAll();
  }).catch(function (e) { document.getElementById("authError").innerText = "Failed to load save."; });
}

function doLogin() {
  const email = document.getElementById("authEmail").value;
  const pass = document.getElementById("authPassword").value;
  document.getElementById("authError").innerText = "Connecting…";
  auth.signInWithEmailAndPassword(email, pass).catch(function (e) { document.getElementById("authError").innerText = "Login failed. Check email/password."; });
}

function doRegister() {
  const email = document.getElementById("authEmail").value;
  const pass = document.getElementById("authPassword").value;
  document.getElementById("authError").innerText = "Creating account…";
  auth.createUserWithEmailAndPassword(email, pass).catch(function (e) { document.getElementById("authError").innerText = "Register failed. Email may be taken."; });
}

function doLogout() { auth.signOut(); }

auth.onAuthStateChanged(function (user) {
  if (user) { currentUser = user; loadUserData(user); }
  else { currentUser = null; state = null; document.getElementById("loginScreen").style.display = "flex"; document.getElementById("gameApp").style.display = "none"; }
});
function repairIbbUrls() {
  const fix = function (u, label) { if (!u || u.indexOf("://ibb.co/") === -1) return u; const code = u.split("://ibb.co/")[1].split("?")[0]; return "https://i.ibb.co/" + code + "/" + (label || "image.png"); };
  for (const m of content.media) m.path = fix(m.path, m.label);
  for (const c of content.characters) if (c.images && c.images.portrait && c.images.portrait.indexOf("://ibb.co/") !== -1) { const med = content.media.find(mm => mm.path === c.images.portrait); c.images.portrait = fix(c.images.portrait, med ? med.label : "image.png"); }
  try { localStorage.setItem(CONTENT_KEY, JSON.stringify(content)); } catch (e) {}
}
function saveState() {
  if (!state) return;
  try { localStorage.setItem("storykeeper_save_local", JSON.stringify(state)); } catch (e) {}
  if (auth.currentUser) { if (isGM()) { try { state.gm_content = content; } catch (e) {} } db.collection("players").doc(auth.currentUser.uid).set(state).catch(function (e) {}); }
}
function loadUserData(user) {
  db.collection("players").doc(user.uid).get().then(function (snap) {
    if (snap.exists) {
      state = snap.data();
      if (isGM() && state.gm_content && state.gm_content.characters) { content = state.gm_content; if (!content.media) content.media = []; if (!content.settings) content.settings = {}; try { localStorage.setItem(CONTENT_KEY, JSON.stringify(content)); } catch (e) {} }
      ensureCollections();
    } else { state = defaultState(); saveState(); }
    repairIbbUrls();
    document.getElementById("loginScreen").style.display = "none";
    document.getElementById("gameApp").style.display = "block";
    document.getElementById("userEmail").innerText = user.email;
    renderAll();
  }).catch(function (e) { document.getElementById("authError").innerText = "Failed to load save."; });
}
(function () {
  const o1 = document.getElementById("imgbbBtn"); if (o1) o1.style.display = "none";
  const o2 = document.getElementById("imgbbBtn2"); if (o2) o2.style.display = "none";
  if (document.getElementById("imgbbBtn3")) return;
  const mediaBox = document.getElementById("deskMedia"); if (!mediaBox) return;
  const inp = document.createElement("input"); inp.type = "file"; inp.accept = "image/*"; inp.id = "imgbbInput3"; inp.style.display = "none";
  const btn = document.createElement("button"); btn.id = "imgbbBtn3"; btn.innerText = "Upload & Assign Photo";
  btn.onclick = function () { inp.click(); };
  inp.addEventListener("change", function () {
    const f = inp.files[0]; if (!f) return;
    const reader = new FileReader();
    reader.onload = function () {
      const b64 = String(reader.result).split(",")[1];
      const fd = new FormData(); fd.append("image", b64); fd.append("name", f.name.replace(/\.[^.]+$/, ""));
      fetch("https://api.imgbb.com/1/upload?key=" + IMGBB_KEY, { method: "POST", body: fd })
        .then(function (r) { return r.json(); })
        .then(function (j) {
          if (j && j.data) {
            const url = j.data.display_url || (j.data.image && j.data.image.url) || j.data.url;
            if (!content.media.some(m => m.path === url)) content.media.push({ id: slugId(f.name) + "_" + (Date.now() % 1000), label: f.name, path: url });
            const base = f.name.replace(/\.[^.]+$/, "");
            const matched = content.characters.find(x => x.id === slugId(base) || x.name.toLowerCase() === base.toLowerCase());
            saveContent(); renderAll();
            deskAssignPicture(url, f.name, matched ? matched.id : (content.characters[0] ? content.characters[0].id : ""));
          } else { alert("Upload failed. ImgBB refused it."); }
        })
        .catch(function () { alert("Upload failed. Check internet."); });
    };
    reader.readAsDataURL(f);
    inp.value = "";
  });
  mediaBox.parentNode.insertBefore(inp, mediaBox.nextSibling);
  mediaBox.parentNode.insertBefore(btn, inp.nextSibling);
})();
(function () {
  if (document.getElementById("toTopBtn")) return;
  const b = document.createElement("button"); b.id = "toTopBtn"; b.innerText = "↑ Top";
  b.style.position = "fixed"; b.style.right = "12px"; b.style.bottom = "12px"; b.style.width = "auto"; b.style.zIndex = "999";
  b.onclick = function () { window.scrollTo({ top: 0, behavior: "smooth" }); };
  document.body.appendChild(b);
})();
(function () {
  const olds = ["imgbbBtn", "imgbbBtn2", "imgbbBtn3"];
  for (const id of olds) { const el = document.getElementById(id); if (el) el.style.display = "none"; }
  if (document.getElementById("cldBtn")) return;
  const mediaBox = document.getElementById("deskMedia"); if (!mediaBox) return;
  const inp = document.createElement("input"); inp.type = "file"; inp.accept = "image/*"; inp.id = "cldInput"; inp.style.display = "none";
  const btn = document.createElement("button"); btn.id = "cldBtn"; btn.innerText = "Upload & Assign Photo";
  btn.onclick = function () { inp.click(); };
  inp.addEventListener("change", function () {
    const f = inp.files[0]; if (!f) return;
    const fd = new FormData();
    fd.append("file", f);
    fd.append("upload_preset", "jnklkxgk");
    fetch("https://api.cloudinary.com/v1_1/equbrwx4/image/upload", { method: "POST", body: fd })
      .then(function (r) { return r.json(); })
      .then(function (j) {
        if (j && j.secure_url) {
          const url = j.secure_url;
          if (!content.media.some(m => m.path === url)) content.media.push({ id: slugId(f.name) + "_" + (Date.now() % 1000), label: f.name, path: url });
          const base = f.name.replace(/\.[^.]+$/, "");
          const matched = content.characters.find(x => x.id === slugId(base) || x.name.toLowerCase() === base.toLowerCase());
          saveContent(); renderAll();
          deskAssignPicture(url, f.name, matched ? matched.id : (content.characters[0] ? content.characters[0].id : ""));
        } else { alert("Upload failed: " + ((j && j.error && j.error.message) || "unknown")); }
      })
      .catch(function () { alert("Upload failed. Check internet."); });
    inp.value = "";
  });
  mediaBox.parentNode.insertBefore(inp, mediaBox.nextSibling);
  mediaBox.parentNode.insertBefore(btn, inp.nextSibling);
})();
function renderDesk() {
  let me = ""; for (const m of content.media) me += "<option value='" + m.id + "'>" + m.label + "</option>";
  document.getElementById("deskMedia").innerHTML = card("<div class='small'>Selected media:</div><select id='deskMediaSelect'>" + (me || "<option value=''>none</option>") + "</select>");
  let ba = ""; for (const b of content.banners) ba += "<option value='" + b.id + "'>" + b.name + "</option>";
  let ch = ""; for (const c of content.characters) ch += "<option value='" + c.id + "'>" + c.name + "</option>";
  let fo = ""; for (const f of content.refreshments) fo += "<option value='" + f.id + "'>" + f.name + "</option>";
  let re = ""; for (const r of content.relationships) re += "<option value='" + r.id + "'>" + r.name + "</option>";
  let ex = ""; for (const e of content.expeditions) ex += "<option value='" + e.id + "'>" + e.name + "</option>";
  document.getElementById("deskBanners").innerHTML = card("<div class='small'>Selected banner:</div><select id='deskBannerSelect'>" + (ba || "<option value=''>none</option>") + "</select>");
  document.getElementById("deskCharacters").innerHTML = card("<div class='small'>Selected character:</div><select id='deskCharSelect'>" + (ch || "<option value=''>none</option>") + "</select>");
  document.getElementById("deskRelationships").innerHTML = card("<div class='small'>Selected relationship:</div><select id='deskRelSelect'>" + (re || "<option value=''>none</option>") + "</select>");
  document.getElementById("deskRefreshments").innerHTML = card("<div class='small'>Selected refreshment:</div><select id='deskFoodSelect'>" + (fo || "<option value=''>none</option>") + "</select>");
  document.getElementById("deskExpeditions").innerHTML = card("<div class='small'>Selected expedition:</div><select id='deskExpSelect'>" + (ex || "<option value=''>none</option>") + "</select>");
  let art = document.getElementById("artControls");
  if (!art) { art = document.createElement("div"); art.id = "artControls"; const mediaBox = document.getElementById("deskMedia"); mediaBox.parentNode.insertBefore(art, mediaBox.nextSibling); }
  art.innerHTML = card("<div class='small'>Set Portrait on:</div><select id='artCharSelect'>" + (ch || "<option value=''>none</option>") + "</select><div class='small'>Set Banner Art on:</div><select id='artBannerSelect'>" + (ba || "<option value=''>none</option>") + "</select><div class='small'>Set Icon on:</div><select id='artFoodSelect'>" + (fo || "<option value=''>none</option>") + "</select>");
}
function deskSetCharacterImage() { const cid = getSelectValue("artCharSelect") || getSelectValue("deskCharSelect"); if (!cid) { alert("Pick a character first."); return; } const path = getSelectedMediaPath(); if (!path) { alert("Add or upload media first."); return; } const c = content.characters.find(x => x.id === cid); if (!c) return; if (!c.images) c.images = {}; c.images.portrait = path; saveContent(); renderAll(); alert(c.name + " portrait set."); }
function deskSetBannerImage() { const bid = getSelectValue("artBannerSelect") || getSelectValue("deskBannerSelect"); if (!bid) { alert("Pick a banner first."); return; } const path = getSelectedMediaPath(); if (!path) { alert("Add or upload media first."); return; } const b = content.banners.find(x => x.id === bid); if (!b) return; if (!b.images) b.images = {}; b.images.background = path; saveContent(); renderAll(); alert(b.name + " art set."); }
function deskSetFoodImage() { const fid = getSelectValue("artFoodSelect") || getSelectValue("deskFoodSelect"); if (!fid) { alert("Pick a refreshment first."); return; } const path = getSelectedMediaPath(); if (!path) { alert("Add or upload media first."); return; } const f = content.refreshments.find(x => x.id === fid); if (!f) return; if (!f.images) f.images = {}; f.images.icon = path; saveContent(); renderAll(); alert(f.name + " icon set."); }
(function () {
  const btns = document.querySelectorAll("#tab-desk button");
  for (const b of btns) { if (b.innerText === "Clear Selected Portrait") b.style.display = "none"; }
})();
function updateStatus() { regenCandlelight(); document.getElementById("currencies").innerHTML = "<span class='cur'>💎 " + state.shards + "</span> <span class='cur'>🪶 " + state.quills + "</span> <span class='cur'>📜 " + state.pages + "</span> <span class='cur'>🕯 " + state.candlelight + "/" + CANDLELIGHT_MAX + "</span>"; }
function repairIbbUrls() { let cleared = 0; const dead = function (u) { return !!u && u.indexOf("ibb.co/") !== -1; }; for (const m of content.media) if (dead(m.path)) { m.path = ""; cleared++; } content.media = content.media.filter(m => m.path !== ""); for (const c of content.characters) if (c.images && dead(c.images.portrait)) { c.images.portrait = ""; cleared++; } if (cleared) { try { localStorage.setItem(CONTENT_KEY, JSON.stringify(content)); } catch (e) {} } }
(function () {
  const st = document.createElement("style");
  st.textContent = ".topbar{flex-direction:column;align-items:stretch;gap:6px}.topbar .actions{justify-content:space-between;align-items:center;width:100%}.topbar #currencies{display:flex;flex-wrap:wrap;gap:6px}.cur{background:#2b2142;padding:4px 8px;border-radius:8px;font-size:13px;color:#d9cff7}#userEmail{font-size:11px}";
  document.head.appendChild(st);
  const ps = document.querySelectorAll("body > p");
  for (const p of ps) { if (p.innerText && p.innerText.indexOf("Step") === 0) p.style.display = "none"; }
})();
function deskOpenForm(title, fields, onSave) { deskFormCallback = onSave; let h = "<div class='card'><strong>" + title + "</strong>"; for (const f of fields) { h += "<div class='small'>" + f.label + "</div>"; if (f.options) { h += "<select id='df_" + f.id + "'>"; for (const o of f.options) h += "<option value='" + o.value + "'" + (String(o.value) === String(f.value) ? " selected" : "") + ">" + o.label + "</option>"; h += "</select>"; } else { h += "<input id='df_" + f.id + "' type='text' value=\"" + String(f.value == null ? "" : f.value).replace(/"/g, "&quot;") + "\">"; } } h += "<button onclick=\"deskSaveForm()\">Save</button><button onclick=\"deskCloseForm()\">Cancel</button></div>"; deskFormContainer().innerHTML = h; deskFormContainer().scrollIntoView({ behavior: "smooth", block: "center" }); }
function deskSendGift() { const types = ["shards", "pages", "quills", "dust", "embers", "stones", "refreshment"].map(function (t) { return { value: t, label: t }; }); const foods = content.refreshments.map(function (f) { return { value: f.id, label: f.name }; }); deskOpenForm("Send Gift", [ { id: "type", label: "Gift type", options: types, value: "shards" }, { id: "idref", label: "If refreshment: which one", options: foods, value: "" }, { id: "amount", label: "Amount", value: "100" }, { id: "note", label: "Note to player", value: "A gift from the Keeper." } ], function () { const type = deskGet("type"); const idref = type === "refreshment" ? deskGet("idref") : ""; state.gifts.push({ id: "gift_" + Date.now(), type: type, idref: idref, amount: parseInt(deskGet("amount")) || 1, note: deskGet("note") }); saveState(); renderGiftBox(); alert("Gift sent! Players claim it in Archive → Gift Box."); }); }
function deskAddRelationship() { const chars = content.characters.map(function (c) { return { value: c.id, label: c.name }; }); deskOpenForm("Add Bond / Couple", [ { id: "m1", label: "Member 1", options: chars, value: "" }, { id: "m2", label: "Member 2", options: chars, value: "" }, { id: "name", label: "Bond name", value: "Bound Hearts" }, { id: "type", label: "Type", options: [{ value: "couple", label: "couple" }, { value: "friend", label: "friend" }, { value: "rival", label: "rival" }], value: "couple" }, { id: "stat", label: "Buff stat", options: [{ value: "hp", label: "HP" }, { value: "atk", label: "ATK" }, { value: "def", label: "DEF" }], value: "atk" }, { id: "value", label: "Buff percent", value: "15" } ], function () { const m1 = deskGet("m1"); const m2 = deskGet("m2"); if (!m1 || !m2 || m1 === m2) { alert("Pick two different members."); return; } const name = deskGet("name") || "Bound Hearts"; const stat = deskGet("stat") || "atk"; const value = parseInt(deskGet("value")) || 15; content.relationships.push({ id: m1 + "_" + m2 + "_" + (deskGet("type") || "couple"), name: name, type: deskGet("type") || "couple", members: [m1, m2], enabled: true, team_buff: { name: name, description: getCharacterName(m1) + " & " + getCharacterName(m2) + " together: " + stat.toUpperCase() + " +" + value + "%.", effects: [{ type: "stat_percent", stat: stat, value: value }] } }); saveContent(); renderAll(); alert("Relationship added."); }); }
function deskEditRelationship() { const id = getSelectValue("deskRelSelect"); if (!id) { alert("No relationship selected."); return; } const r = content.relationships.find(x => x.id === id); if (!r) return; const chars = content.characters.map(function (c) { return { value: c.id, label: c.name }; }); const eff = r.team_buff.effects[0] || { stat: "atk", value: 15 }; deskOpenForm("Edit Relationship", [ { id: "m1", label: "Member 1", options: chars, value: r.members[0] }, { id: "m2", label: "Member 2", options: chars, value: r.members[1] }, { id: "name", label: "Bond name", value: r.name }, { id: "type", label: "Type", options: [{ value: "couple", label: "couple" }, { value: "friend", label: "friend" }, { value: "rival", label: "rival" }], value: r.type }, { id: "stat", label: "Buff stat", options: [{ value: "hp", label: "HP" }, { value: "atk", label: "ATK" }, { value: "def", label: "DEF" }], value: eff.stat }, { id: "value", label: "Buff percent", value: eff.value } ], function () { const m1 = deskGet("m1"); const m2 = deskGet("m2"); if (!m1 || !m2 || m1 === m2) { alert("Pick two different members."); return; } r.members = [m1, m2]; r.name = deskGet("name") || r.name; r.type = deskGet("type") || r.type; let e = r.team_buff.effects[0] || { type: "stat_percent" }; e.stat = deskGet("stat") || e.stat; e.value = parseInt(deskGet("value")) || e.value; r.team_buff.effects = [e]; r.team_buff.name = r.name; r.team_buff.description = getCharacterName(m1) + " & " + getCharacterName(m2) + " together: " + e.stat.toUpperCase() + " +" + e.value + "%."; saveContent(); renderAll(); alert("Relationship updated."); }); }
function deskOpenForm(title, fields, onSave) { deskFormCallback = onSave; let h = "<div class='card'><strong>" + title + "</strong>"; for (const f of fields) { h += "<div class='small'>" + f.label + "</div>"; if (f.options) { h += "<select id='df_" + f.id + "'>"; for (const o of f.options) h += "<option value='" + o.value + "'" + (String(o.value) === String(f.value) ? " selected" : "") + ">" + o.label + "</option>"; h += "</select>"; } else { h += "<input id='df_" + f.id + "' type='text' value=\"" + String(f.value == null ? "" : f.value).replace(/"/g, "&quot;") + "\">"; } } h += "<button onclick=\"deskSaveForm()\">Save</button><button onclick=\"deskCloseForm()\">Cancel</button></div>"; deskFormContainer().innerHTML = h; deskFormContainer().scrollIntoView({ behavior: "smooth", block: "center" }); }
const RELATION_LINES = { couple: ["I always feel safe when you are near.", "Your hand fits mine perfectly.", "When this story ends, I want you in every ending.", "You make quiet moments feel like magic.", "I choose you. In every volume, every world."], friend: ["Want to go on an adventure together?", "I saved a snack just for you.", "You never have to pretend around me.", "Let's stay up late and read tonight.", "With you, even boring pages are fun."], rival: ["I'll beat you next time. Just watch.", "Don't think this means I like you.", "Hmph. You're not completely useless.", "Race you to the next chapter!", "One day my name will be above yours."], family: ["You forgot your scarf again, didn't you?", "Home is wherever you are.", "I'll always save a seat for you.", "You've grown so much. I'm proud of you.", "No matter what happens, we're family."] };
function deskAddRelationship() { const chars = content.characters.map(function (c) { return { value: c.id, label: c.name }; }); const types = ["couple", "friend", "rival", "family"].map(function (t) { return { value: t, label: t }; }); deskOpenForm("Add Bond", [ { id: "m1", label: "Member 1", options: chars, value: "" }, { id: "m2", label: "Member 2", options: chars, value: "" }, { id: "name", label: "Bond name", value: "Bound Hearts" }, { id: "type", label: "Type", options: types, value: "couple" }, { id: "stat", label: "Buff stat", options: [{ value: "hp", label: "HP" }, { value: "atk", label: "ATK" }, { value: "def", label: "DEF" }], value: "atk" }, { id: "value", label: "Buff percent", value: "15" } ], function () { const m1 = deskGet("m1"); const m2 = deskGet("m2"); if (!m1 || !m2 || m1 === m2) { alert("Pick two different members."); return; } const type = deskGet("type") || "couple"; const name = deskGet("name") || "Bound Hearts"; const stat = deskGet("stat") || "atk"; const value = parseInt(deskGet("value")) || 15; content.relationships.push({ id: m1 + "_" + m2 + "_" + type, name: name, type: type, members: [m1, m2], enabled: true, lines: (RELATION_LINES[type] || []).slice(), team_buff: { name: name, description: getCharacterName(m1) + " & " + getCharacterName(m2) + " together: " + stat.toUpperCase() + " +" + value + "%.", effects: [{ type: "stat_percent", stat: stat, value: value }] } }); saveContent(); renderAll(); alert("Bond added! Use Edit Bond Lines to customize their talk."); }); }
function deskEditRelLines() { const id = getSelectValue("deskRelSelect"); if (!id) { alert("No relationship selected."); return; } const r = content.relationships.find(x => x.id === id); if (!r) return; const cur = r.lines || RELATION_LINES[r.type] || RELATION_LINES.friend; const fields = []; for (let i = 0; i < 5; i++) fields.push({ id: "l" + i, label: "Line " + (i + 1) + " (spoken alternately)", value: cur[i] || "" }); deskOpenForm("Edit Bond Lines: " + r.name, fields, function () { const lines = []; for (let i = 0; i < 5; i++) { const t = deskGet("l" + i); if (t) lines.push(t); } r.lines = lines; if (!content.reading_room) content.reading_room = {}; if (!content.reading_room.pair_scenes) content.reading_room.pair_scenes = []; const sceneId = "rel_" + r.id; const pl = []; for (let i = 0; i < lines.length; i++) pl.push({ character: (i % 2 === 0 ? r.members[0] : r.members[1]), text: lines[i] }); const ex = content.reading_room.pair_scenes.find(s => s.id === sceneId); if (ex) { ex.lines = pl; ex.name = r.name; ex.members = r.members; } else content.reading_room.pair_scenes.push({ id: sceneId, name: r.name, members: r.members, bookmark: r.name + " share a moment.", lines: pl, background: "" }); saveContent(); renderAll(); alert("Bond lines saved! Put both characters in Reading to see them."); }); }
function deskEditSoloLines() { const id = getSelectValue("deskCharSelect"); if (!id) { alert("No character selected."); return; } const c = content.characters.find(x => x.id === id); if (!c) return; if (!content.reading_room) content.reading_room = {}; if (!content.reading_room.solo_lines) content.reading_room.solo_lines = {}; const cur = content.reading_room.solo_lines[id] || []; const fields = []; for (let i = 0; i < 5; i++) fields.push({ id: "s" + i, label: "Line " + (i + 1), value: cur[i] || "" }); deskOpenForm("Edit Solo Lines: " + c.name, fields, function () { const lines = []; for (let i = 0; i < 5; i++) { const t = deskGet("s" + i); if (t) lines.push(t); } content.reading_room.solo_lines[id] = lines; saveContent(); renderAll(); alert("Solo lines saved! Put one character in Reading to see them."); }); }
(function () { const relBox = document.getElementById("deskRelationships"); if (relBox && !document.getElementById("relLinesBtn")) { const b = document.createElement("button"); b.id = "relLinesBtn"; b.innerText = "Edit Bond Lines"; b.onclick = deskEditRelLines; relBox.parentNode.insertBefore(b, relBox.nextSibling); } const charBox = document.getElementById("deskCharacters"); if (charBox && !document.getElementById("soloLinesBtn")) { const b = document.createElement("button"); b.id = "soloLinesBtn"; b.innerText = "Edit Solo Lines"; b.onclick = deskEditSoloLines; charBox.parentNode.insertBefore(b, charBox.nextSibling); } })();
function saveContent() { try { localStorage.setItem(CONTENT_KEY, JSON.stringify(content)); } catch (e) {} if (typeof isGM === "function" && isGM() && auth.currentUser) { try { state.gm_content = content; db.collection("players").doc(auth.currentUser.uid).set(state).catch(function () {}); } catch (e) {} } }
function renderInventory() { ensureCollections(); let opts = ""; for (const f of content.refreshments) { const n = state.inventory[f.id] || 0; if (n > 0) opts += "<option value='" + f.id + "'>" + f.name + " x" + n + "</option>"; } let ch = ""; for (const cid in state.owned) { const c = content.characters.find(x => x.id === cid); if (c) ch += "<option value='" + c.id + "'>" + c.name + "</option>"; } document.getElementById("inventory").innerHTML = card("<div class='small'>Companion:</div><select id='archCharSelect'>" + (ch || "<option value=''>none</option>") + "</select><div class='small'>Refreshment:</div><select id='archFoodSelect'>" + (opts || "<option value=''>none owned</option>") + "</select><button onclick=\"feedPicked()\">Feed</button>"); }
function feedPicked() { const cid = getSelectValue("archCharSelect"); if (!cid) { alert("Pick a companion."); return; } selectedCharacterId = cid; const fid = getSelectValue("archFoodSelect"); if (!fid) { alert("No refreshment owned."); return; } feedFood(fid); renderInventory(); }
(function () { const b = document.getElementById("charLinesBtn"); if (b) b.style.display = "none"; })();
function ensureArtifacts() { if (!content.artifacts) content.artifacts = []; if (!state.artifactsInv) state.artifactsInv = {}; if (!state.equipped) state.equipped = {}; }
function artifactBonuses(cid) { ensureArtifacts(); const b = { hp: 0, atk: 0, def: 0 }; for (const aid of (state.equipped[cid] || [])) { const a = content.artifacts.find(x => x.id === aid); if (a && a.stats) { b.hp += a.stats.hp || 0; b.atk += a.stats.atk || 0; b.def += a.stats.def || 0; } } return b; }
function renderDeskArtifacts() { ensureArtifacts(); let op = ""; for (const a of content.artifacts) op += "<option value='" + a.id + "'>" + a.name + " (" + a.type + ")</option>"; const el = document.getElementById("deskArtifacts"); if (el) el.innerHTML = card("<div class='small'>Selected artifact:</div><select id='deskArtSelect'>" + (op || "<option value=''>none</option>") + "</select>"); }
function deskAddArtifact() { deskOpenForm("Add Artifact / Weapon", [ { id: "name", label: "Name" }, { id: "type", label: "Type", options: [{ value: "weapon", label: "weapon" }, { value: "armor", label: "armor" }, { value: "trinket", label: "trinket" }, { value: "relic", label: "relic" }], value: "weapon" }, { id: "rarity", label: "Rarity (3,4,5)", value: "4" }, { id: "hp", label: "HP bonus", value: "0" }, { id: "atk", label: "ATK bonus", value: "50" }, { id: "def", label: "DEF bonus", value: "0" }, { id: "desc", label: "Description", value: "A trusted weapon." } ], function () { const name = deskGet("name"); if (!name) { alert("Name required."); return; } ensureArtifacts(); let id = slugId(name); if (content.artifacts.some(a => a.id === id)) id = id + "_" + (Date.now() % 1000); content.artifacts.push({ id: id, name: name, type: deskGet("type"), rarity: parseInt(deskGet("rarity")) || 4, stats: { hp: parseInt(deskGet("hp")) || 0, atk: parseInt(deskGet("atk")) || 0, def: parseInt(deskGet("def")) || 0 }, desc: deskGet("desc"), images: { icon: "" } }); saveContent(); renderAll(); alert("Artifact added: " + name); }); }
function deskEditArtifact() { ensureArtifacts(); const id = getSelectValue("deskArtSelect"); if (!id) { alert("No artifact selected."); return; } const a = content.artifacts.find(x => x.id === id); if (!a) return; deskOpenForm("Edit Artifact", [ { id: "name", label: "Name", value: a.name }, { id: "type", label: "Type", options: [{ value: "weapon", label: "weapon" }, { value: "armor", label: "armor" }, { value: "trinket", label: "trinket" }, { value: "relic", label: "relic" }], value: a.type }, { id: "rarity", label: "Rarity", value: a.rarity }, { id: "hp", label: "HP bonus", value: a.stats.hp }, { id: "atk", label: "ATK bonus", value: a.stats.atk }, { id: "def", label: "DEF bonus", value: a.stats.def }, { id: "desc", label: "Description", value: a.desc } ], function () { a.name = deskGet("name") || a.name; a.type = deskGet("type"); a.rarity = parseInt(deskGet("rarity")) || a.rarity; a.stats = { hp: parseInt(deskGet("hp")) || 0, atk: parseInt(deskGet("atk")) || 0, def: parseInt(deskGet("def")) || 0 }; a.desc = deskGet("desc"); saveContent(); renderAll(); alert("Artifact updated."); }); }
function deskDeleteArtifact() { ensureArtifacts(); const id = getSelectValue("deskArtSelect"); if (!id) { alert("No artifact selected."); return; } if (!confirm("Delete this artifact?")) return; content.artifacts = content.artifacts.filter(a => a.id !== id); for (const k in state.equipped) state.equipped[k] = (state.equipped[k] || []).filter(x => x !== id); saveContent(); saveState(); renderAll(); alert("Artifact deleted."); }
function showTab(t) { if (t === "desk" && !isGM()) t = "inscribe"; currentTab = t; const pages = document.querySelectorAll(".tab-page"); for (const p of pages) p.style.display = (p.id === "tab-" + t) ? "block" : "none"; const btns = document.querySelectorAll(".tabs button"); for (const b of btns) b.classList.toggle("active", b.id === "tab-btn-" + t); renderAll(); }
function renderArtifactsTab() { ensureArtifacts(); let ch = ""; for (const cid in state.owned) { const c = content.characters.find(x => x.id === cid); if (c) ch += "<option value='" + cid + "'" + (cid === window.__artChar ? " selected" : "") + ">" + c.name + "</option>"; } let cid = window.__artChar; if (!cid || !state.owned[cid]) { cid = ""; for (const k in state.owned) { cid = k; break; } } window.__artChar = cid; let h = card("<div class='small'>Companion:</div><select id='artCharSel' onchange=\"window.__artChar=this.value;renderArtifactsTab()\">" + (ch || "<option value=''>none</option>") + "</select>"); if (cid) { const b = artifactBonuses(cid); const eqList = state.equipped[cid] || []; h += "<div class='small'>Equipped bonuses: +" + b.hp + " HP · +" + b.atk + " ATK · +" + b.def + " DEF</div>"; for (let i = 0; i < eqList.length; i++) { const a = content.artifacts.find(x => x.id === eqList[i]); h += "<div class='result-item'>" + (a ? a.name : "?") + "<button onclick=\"unequipArtifact('" + cid + "'," + i + ")\">Remove</button></div>"; } if (eqList.length < 4) { let inv = ""; for (const a of content.artifacts) { const owned = state.artifactsInv[a.id] || 0; const used = eqList.filter(x => x === a.id).length; if (owned > used) inv += "<option value='" + a.id + "'>" + a.name + " (x" + (owned - used) + ")</option>"; } h += "<div class='small'>Equip:</div><select id='artEquipSel'>" + (inv || "<option value=''>none available</option>") + "</select><button onclick=\"equipArtifact('" + cid + "')\">Equip</button>"; } } document.getElementById("artifactEquip").innerHTML = h; let ih = ""; for (const a of content.artifacts) { const n = state.artifactsInv[a.id] || 0; if (n > 0) ih += "<div class='result-item'><span class='rarity-" + a.rarity + "'>" + a.name + "</span> x" + n + "<div class='small'>" + a.type + " · +" + (a.stats.hp || 0) + " HP +" + (a.stats.atk || 0) + " ATK +" + (a.stats.def || 0) + " DEF</div></div>"; } document.getElementById("artifactInv").innerHTML = ih || card("No artifacts yet. Get them from gifts!"); }
function equipArtifact(cid) { const aid = getSelectValue("artEquipSel"); if (!aid) { alert("None available."); return; } ensureArtifacts(); if (!state.equipped[cid]) state.equipped[cid] = []; if (state.equipped[cid].length >= 4) { alert("Max 4 artifacts."); return; } state.equipped[cid].push(aid); saveState(); renderAll(); }
function unequipArtifact(cid, i) { state.equipped[cid].splice(i, 1); saveState(); renderAll(); }
function appendCharBonuses() { const c = content.characters.find(x => x.id === selectedCharacterId); const el = document.getElementById("characterDetail"); if (!c || !el) return; const b = artifactBonuses(c.id); const eqn = ((state.equipped && state.equipped[c.id]) || []).length; if (eqn) el.innerHTML += card("<div class='small'>Artifacts (" + eqn + "): +" + b.hp + " HP · +" + b.atk + " ATK · +" + b.def + " DEF</div>"); }
const __origRenderAll = renderAll;
function renderAll() { __origRenderAll(); renderDeskArtifacts(); const at = document.getElementById("tab-artifacts"); if (at && at.style.display !== "none") renderArtifactsTab(); appendCharBonuses(); }
function deskSendGift() { const types = ["shards", "pages", "quills", "dust", "embers", "stones", "refreshment", "artifact"].map(function (t) { return { value: t, label: t }; }); const foods = content.refreshments.map(function (f) { return { value: f.id, label: f.name }; }); const arts = (content.artifacts || []).map(function (a) { return { value: a.id, label: a.name }; }); deskOpenForm("Send Gift", [ { id: "type", label: "Gift type", options: types, value: "shards" }, { id: "idref", label: "If refreshment", options: foods, value: "" }, { id: "idref2", label: "If artifact", options: arts, value: "" }, { id: "amount", label: "Amount", value: "1" }, { id: "note", label: "Note", value: "A gift from the Keeper." } ], function () { const type = deskGet("type"); const idref = type === "refreshment" ? deskGet("idref") : (type === "artifact" ? deskGet("idref2") : ""); state.gifts.push({ id: "gift_" + Date.now(), type: type, idref: idref, amount: parseInt(deskGet("amount")) || 1, note: deskGet("note") }); saveState(); renderGiftBox(); alert("Gift sent!"); }); }
function claimGift(gid) { const g = state.gifts.find(x => x.id === gid); if (!g) return; if (g.type === "shards") state.shards += g.amount; else if (g.type === "pages") state.pages += g.amount; else if (g.type === "quills") state.quills += g.amount; else if (g.type === "dust") state.materials.vellum_dust = (state.materials.vellum_dust || 0) + g.amount; else if (g.type === "embers") state.materials.lumina_embers = (state.materials.lumina_embers || 0) + g.amount; else if (g.type === "stones") state.materials.mythos_stones = (state.materials.mythos_stones || 0) + g.amount; else if (g.type === "refreshment") state.inventory[g.idref] = (state.inventory[g.idref] || 0) + g.amount; else if (g.type === "artifact") { ensureArtifacts(); state.artifactsInv[g.idref] = (state.artifactsInv[g.idref] || 0) + g.amount; } state.gifts = state.gifts.filter(x => x.id !== gid); saveState(); renderAll(); alert("Claimed!"); }
(function () { if (document.getElementById("deskArtifacts")) return; const desk = document.getElementById("tab-desk"); const w = document.createElement("div"); w.innerHTML = "<h3>Artifacts / Weapons</h3><div id='deskArtifacts'></div><button onclick='deskAddArtifact()'>Add</button><button onclick='deskEditArtifact()'>Edit</button><button onclick='deskDeleteArtifact()'>Delete</button>"; desk.appendChild(w); })();
(function () { if (document.getElementById("tab-btn-artifacts")) return; const tabs = document.querySelector(".tabs"); const b = document.createElement("button"); b.id = "tab-btn-artifacts"; b.innerText = "Artifacts"; b.onclick = function () { showTab("artifacts"); }; tabs.appendChild(b); const p = document.createElement("div"); p.id = "tab-artifacts"; p.className = "tab-page"; p.style.display = "none"; p.innerHTML = "<h3>Equip Artifacts</h3><div id='artifactEquip'></div><h3>Artifact Inventory</h3><div id='artifactInv'></div>"; document.getElementById("gameApp").appendChild(p); })();
function ensureMaterialDefs() { if (!content.material_defs) content.material_defs = [{ id: "vellum_dust", name: "Vellum Dust", icon: "✨" }, { id: "lumina_embers", name: "Lumina Embers", icon: "🔥" }, { id: "mythos_stones", name: "Mythos Stones", icon: "💎" }]; if (!state.materials) state.materials = {}; }
function matName(id) { ensureMaterialDefs(); const d = content.material_defs.find(m => m.id === id); return d ? d.name : id; }
function renderMaterials() { ensureMaterialDefs(); let h = ""; for (const d of content.material_defs) h += "<div>" + (d.icon || "•") + " " + d.name + ": " + (state.materials[d.id] || 0) + "</div>"; document.getElementById("materials").innerHTML = card(h); }
function deskAddMaterial() { deskOpenForm("Add Material", [{ id: "name", label: "Name" }, { id: "icon", label: "Icon (emoji)", value: "🌸" }], function () { const name = deskGet("name"); if (!name) { alert("Name required."); return; } ensureMaterialDefs(); const id = slugId(name); if (content.material_defs.some(m => m.id === id)) { alert("Already exists."); return; } content.material_defs.push({ id: id, name: name, icon: deskGet("icon") || "•" }); if (state.materials[id] == null) state.materials[id] = 0; saveContent(); saveState(); renderAll(); alert("Material added: " + name); }); }
function deskDeleteMaterial() { ensureMaterialDefs(); const id = getSelectValue("deskMatSelect"); if (!id) { alert("No material selected."); return; } if (!confirm("Delete this material?")) return; content.material_defs = content.material_defs.filter(m => m.id !== id); saveContent(); renderAll(); alert("Material deleted."); }
function artifactBonuses(cid) { ensureArtifacts(); if (!state.artifactLevels) state.artifactLevels = {}; const b = { hp: 0, atk: 0, def: 0 }; for (const aid of (state.equipped[cid] || [])) { const a = content.artifacts.find(x => x.id === aid); if (a && a.stats) { const lvl = state.artifactLevels[aid] || 1; const mult = 1 + 0.05 * (lvl - 1); b.hp += Math.round((a.stats.hp || 0) * mult); b.atk += Math.round((a.stats.atk || 0) * mult); b.def += Math.round((a.stats.def || 0) * mult); } } return b; }
function levelArtifact(aid) { ensureArtifacts(); ensureMaterialDefs(); if (!state.artifactLevels) state.artifactLevels = {}; const lvl = state.artifactLevels[aid] || 1; if (lvl >= 20) { alert("Max level (20)."); return; } const a = content.artifacts.find(x => x.id === aid); if (!a) return; const pagesCost = lvl * 100; const matId = a.material || "vellum_dust"; const matCount = 1 + Math.floor(lvl / 5); if (state.pages < pagesCost) { alert("Need " + pagesCost + " Pages."); return; } if ((state.materials[matId] || 0) < matCount) { alert("Need " + matCount + " " + matName(matId) + "."); return; } state.pages -= pagesCost; state.materials[matId] -= matCount; state.artifactLevels[aid] = lvl + 1; saveState(); renderAll(); alert(a.name + " is now level " + (lvl + 1) + "!"); }
function deskAddArtifact() { ensureMaterialDefs(); const mats = content.material_defs.map(function (m) { return { value: m.id, label: m.name }; }); deskOpenForm("Add Artifact / Weapon", [ { id: "name", label: "Name" }, { id: "type", label: "Type", options: [{ value: "weapon", label: "weapon" }, { value: "armor", label: "armor" }, { value: "trinket", label: "trinket" }, { value: "relic", label: "relic" }], value: "weapon" }, { id: "rarity", label: "Rarity (3,4,5)", value: "4" }, { id: "hp", label: "HP bonus", value: "0" }, { id: "atk", label: "ATK bonus", value: "50" }, { id: "def", label: "DEF bonus", value: "0" }, { id: "material", label: "Level-up material", options: mats, value: "vellum_dust" }, { id: "desc", label: "Description", value: "A trusted weapon." } ], function () { const name = deskGet("name"); if (!name) { alert("Name required."); return; } ensureArtifacts(); let id = slugId(name); if (content.artifacts.some(a => a.id === id)) id = id + "_" + (Date.now() % 1000); content.artifacts.push({ id: id, name: name, type: deskGet("type"), rarity: parseInt(deskGet("rarity")) || 4, stats: { hp: parseInt(deskGet("hp")) || 0, atk: parseInt(deskGet("atk")) || 0, def: parseInt(deskGet("def")) || 0 }, material: deskGet("material"), desc: deskGet("desc"), images: { icon: "" } }); saveContent(); renderAll(); alert("Artifact added: " + name); }); }
function deskEditArtifact() { ensureArtifacts(); ensureMaterialDefs(); const id = getSelectValue("deskArtSelect"); if (!id) { alert("No artifact selected."); return; } const a = content.artifacts.find(x => x.id === id); if (!a) return; const mats = content.material_defs.map(function (m) { return { value: m.id, label: m.name }; }); deskOpenForm("Edit Artifact", [ { id: "name", label: "Name", value: a.name }, { id: "type", label: "Type", options: [{ value: "weapon", label: "weapon" }, { value: "armor", label: "armor" }, { value: "trinket", label: "trinket" }, { value: "relic", label: "relic" }], value: a.type }, { id: "rarity", label: "Rarity", value: a.rarity }, { id: "hp", label: "HP bonus", value: a.stats.hp }, { id: "atk", label: "ATK bonus", value: a.stats.atk }, { id: "def", label: "DEF bonus", value: a.stats.def }, { id: "material", label: "Level-up material", options: mats, value: a.material || "vellum_dust" }, { id: "desc", label: "Description", value: a.desc } ], function () { a.name = deskGet("name") || a.name; a.type = deskGet("type"); a.rarity = parseInt(deskGet("rarity")) || a.rarity; a.stats = { hp: parseInt(deskGet("hp")) || 0, atk: parseInt(deskGet("atk")) || 0, def: parseInt(deskGet("def")) || 0 }; a.material = deskGet("material"); a.desc = deskGet("desc"); saveContent(); renderAll(); alert("Artifact updated."); }); }
function renderArtifactsTab() { ensureArtifacts(); if (!state.artifactLevels) state.artifactLevels = {}; let ch = ""; for (const cid in state.owned) { const c = content.characters.find(x => x.id === cid); if (c) ch += "<option value='" + cid + "'" + (cid === window.__artChar ? " selected" : "") + ">" + c.name + "</option>"; } let cid = window.__artChar; if (!cid || !state.owned[cid]) { cid = ""; for (const k in state.owned) { cid = k; break; } } window.__artChar = cid; let h = card("<div class='small'>Companion:</div><select id='artCharSel' onchange=\"window.__artChar=this.value;renderArtifactsTab()\">" + (ch || "<option value=''>none</option>") + "</select>"); if (cid) { const b = artifactBonuses(cid); const eqList = state.equipped[cid] || []; h += "<div class='small'>Equipped bonuses: +" + b.hp + " HP · +" + b.atk + " ATK · +" + b.def + " DEF</div>"; for (let i = 0; i < eqList.length; i++) { const a = content.artifacts.find(x => x.id === eqList[i]); const lvl = state.artifactLevels[eqList[i]] || 1; h += "<div class='result-item'>" + (a ? a.name : "?") + " Lv" + lvl + "<button onclick=\"unequipArtifact('" + cid + "'," + i + ")\">Remove</button></div>"; } if (eqList.length < 4) { let inv = ""; for (const a of content.artifacts) { const owned = state.artifactsInv[a.id] || 0; const used = eqList.filter(x => x === a.id).length; if (owned > used) inv += "<option value='" + a.id + "'>" + a.name + " (x" + (owned - used) + ")</option>"; } h += "<div class='small'>Equip:</div><select id='artEquipSel'>" + (inv || "<option value=''>none available</option>") + "</select><button onclick=\"equipArtifact('" + cid + "')\">Equip</button>"; } } document.getElementById("artifactEquip").innerHTML = h; let ih = ""; for (const a of content.artifacts) { const n = state.artifactsInv[a.id] || 0; if (n > 0) { const lvl = state.artifactLevels[a.id] || 1; ih += "<div class='result-item'><span class='rarity-" + a.rarity + "'>" + a.name + "</span> x" + n + " · Lv " + lvl + "/20<div class='small'>" + a.type + " · +" + (a.stats.hp || 0) + " HP +" + (a.stats.atk || 0) + " ATK +" + (a.stats.def || 0) + " DEF · needs " + matName(a.material || "vellum_dust") + "</div><button onclick=\"levelArtifact('" + a.id + "')\">Level Up (" + (lvl * 100) + " Pages)</button></div>"; } } document.getElementById("artifactInv").innerHTML = ih || card("No artifacts yet. Get them from gifts!"); }
(function () { if (document.getElementById("deskMaterials")) return; const desk = document.getElementById("tab-desk"); const w = document.createElement("div"); w.innerHTML = "<h3>Materials</h3><div id='deskMaterials'></div><button onclick='deskAddMaterial()'>Add</button><button onclick='deskDeleteMaterial()'>Delete</button>"; desk.appendChild(w); })();
function renderDeskArtifacts() { ensureArtifacts(); let op = ""; for (const a of content.artifacts) op += "<option value='" + a.id + "'>" + a.name + " (" + a.type + ")</option>"; const el = document.getElementById("deskArtifacts"); if (el) el.innerHTML = card("<div class='small'>Selected artifact:</div><select id='deskArtSelect'>" + (op || "<option value=''>none</option>") + "</select>"); let mo = ""; ensureMaterialDefs(); for (const m of content.material_defs) mo += "<option value='" + m.id + "'>" + m.name + "</option>"; const mel = document.getElementById("deskMaterials"); if (mel) mel.innerHTML = card("<div class='small'>Selected material:</div><select id='deskMatSelect'>" + (mo || "<option value=''>none</option>") + "</select>"); }

function getCharLines(cid, cat) { if (!content.char_lines) content.char_lines = {}; if (!content.char_lines[cid]) content.char_lines[cid] = {}; if (!content.char_lines[cid][cat]) content.char_lines[cid][cat] = []; return content.char_lines[cid][cat]; }
function ensureStory() { if (!content.story) content.story = { volumes: [] }; if (!state.story) state.story = { cleared: {} }; }
function renderDeskStory() { ensureStory(); let vo = ""; for (const v of content.story.volumes) vo += "<option value='" + v.id + "'>" + v.name + "</option>"; const vel = document.getElementById("deskStoryVol"); if (vel) vel.innerHTML = card("<div class='small'>Selected volume:</div><select id='deskVolSelect'>" + (vo || "<option value=''>none</option>") + "</select>"); const vid = getSelectValue("deskVolSelect"); const v = content.story.volumes.find(x => x.id === vid); let co = ""; if (v) for (const c of v.chapters) co += "<option value='" + c.id + "'>" + c.name + "</option>"; const cel = document.getElementById("deskStoryChap"); if (cel) cel.innerHTML = card("<div class='small'>Selected chapter:</div><select id='deskChapSelect'>" + (co || "<option value=''>none</option>") + "</select>"); }
function deskAddVolume() { deskOpenForm("Add Volume", [{ id: "name", label: "Volume name", value: "Volume 1" }], function () { const name = deskGet("name") || "Volume"; ensureStory(); let id = slugId(name); if (content.story.volumes.some(v => v.id === id)) id += "_" + (Date.now() % 1000); content.story.volumes.push({ id: id, name: name, chapters: [] }); saveContent(); renderAll(); alert("Volume added."); }); }
function deskDeleteVolume() { ensureStory(); const id = getSelectValue("deskVolSelect"); if (!id) { alert("No volume selected."); return; } if (!confirm("Delete volume and its chapters?")) return; content.story.volumes = content.story.volumes.filter(v => v.id !== id); saveContent(); renderAll(); alert("Volume deleted."); }
function deskAddChapter() { ensureStory(); ensureMaterialDefs(); const vid = getSelectValue("deskVolSelect"); const v = content.story.volumes.find(x => x.id === vid); if (!v) { alert("Add a volume first."); return; } const mats = content.material_defs.map(function (m) { return { value: m.id, label: m.name }; }); const arts = [{ value: "", label: "none" }].concat((content.artifacts || []).filter(function (a) { return a.rarity <= 4; }).map(function (a) { return { value: a.id, label: a.name }; })); deskOpenForm("Add Chapter", [ { id: "name", label: "Chapter name", value: "Chapter 1" }, { id: "ename", label: "Villain name", value: "Shadow Thief" }, { id: "ehp", label: "Villain HP", value: "2000" }, { id: "eatk", label: "Villain ATK", value: "100" }, { id: "edef", label: "Villain DEF", value: "50" }, { id: "boss", label: "Boss fight?", options: [{ value: "no", label: "no" }, { value: "yes", label: "yes" }], value: "no" }, { id: "v1", label: "Villain evil line 1", value: "You dare enter my domain?" }, { id: "v2", label: "Villain evil line 2", value: "I'll crush you!" }, { id: "v3", label: "Villain evil line 3", value: "Impossible...!" }, { id: "pages", label: "Reward: Pages", value: "200" }, { id: "levels", label: "Reward: +Levels to team", value: "1" }, { id: "m1", label: "Reward material 1", options: mats, value: "vellum_dust" }, { id: "m1a", label: "Amount 1", value: "2" }, { id: "m2", label: "Reward material 2 (optional)", options: [{ value: "", label: "none" }].concat(mats), value: "" }, { id: "m2a", label: "Amount 2", value: "1" }, { id: "art", label: "Reward artifact (3-4★)", options: arts, value: "" } ], function () { const name = deskGet("name") || "Chapter"; let id = slugId(name); if (v.chapters.some(c => c.id === id)) id += "_" + (Date.now() % 1000); const materials = [{ id: deskGet("m1"), amount: parseInt(deskGet("m1a")) || 1 }]; if (deskGet("m2")) materials.push({ id: deskGet("m2"), amount: parseInt(deskGet("m2a")) || 1 }); v.chapters.push({ id: id, name: name, enemy: { name: deskGet("ename"), hp: parseInt(deskGet("ehp")) || 1000, atk: parseInt(deskGet("eatk")) || 80, def: parseInt(deskGet("edef")) || 40 }, boss: deskGet("boss") === "yes", villain_lines: [deskGet("v1"), deskGet("v2"), deskGet("v3")].filter(Boolean), rewards: { pages: parseInt(deskGet("pages")) || 0, levels: parseInt(deskGet("levels")) || 0, materials: materials, artifact: deskGet("art") || "" } }); saveContent(); renderAll(); alert("Chapter added."); }); }
function deskEditChapter() { ensureStory(); const vid = getSelectValue("deskVolSelect"); const cid = getSelectValue("deskChapSelect"); const v = content.story.volumes.find(x => x.id === vid); if (!v) { alert("No volume."); return; } const c = v.chapters.find(x => x.id === cid); if (!c) { alert("No chapter."); return; } ensureMaterialDefs(); const mats = content.material_defs.map(function (m) { return { value: m.id, label: m.name }; }); const arts = [{ value: "", label: "none" }].concat((content.artifacts || []).filter(function (a) { return a.rarity <= 4; }).map(function (a) { return { value: a.id, label: a.name }; })); const rw = c.rewards || {}; const m1 = (rw.materials && rw.materials[0]) || { id: "vellum_dust", amount: 1 }; const m2 = (rw.materials && rw.materials[1]) || { id: "", amount: 1 }; deskOpenForm("Edit Chapter", [ { id: "name", label: "Chapter name", value: c.name }, { id: "ename", label: "Villain name", value: c.enemy.name }, { id: "ehp", label: "Villain HP", value: c.enemy.hp }, { id: "eatk", label: "Villain ATK", value: c.enemy.atk }, { id: "edef", label: "Villain DEF", value: c.enemy.def }, { id: "boss", label: "Boss fight?", options: [{ value: "no", label: "no" }, { value: "yes", label: "yes" }], value: c.boss ? "yes" : "no" }, { id: "v1", label: "Villain evil line 1", value: (c.villain_lines || [])[0] || "" }, { id: "v2", label: "Villain evil line 2", value: (c.villain_lines || [])[1] || "" }, { id: "v3", label: "Villain evil line 3", value: (c.villain_lines || [])[2] || "" }, { id: "pages", label: "Reward: Pages", value: rw.pages || 0 }, { id: "levels", label: "Reward: +Levels to team", value: rw.levels || 0 }, { id: "m1", label: "Reward material 1", options: mats, value: m1.id }, { id: "m1a", label: "Amount 1", value: m1.amount }, { id: "m2", label: "Reward material 2 (optional)", options: [{ value: "", label: "none" }].concat(mats), value: m2.id }, { id: "m2a", label: "Amount 2", value: m2.amount }, { id: "art", label: "Reward artifact (3-4★)", options: arts, value: rw.artifact || "" } ], function () { c.name = deskGet("name") || c.name; c.enemy = { name: deskGet("ename"), hp: parseInt(deskGet("ehp")) || 1000, atk: parseInt(deskGet("eatk")) || 80, def: parseInt(deskGet("edef")) || 40 }; c.boss = deskGet("boss") === "yes"; c.villain_lines = [deskGet("v1"), deskGet("v2"), deskGet("v3")].filter(Boolean); const materials = [{ id: deskGet("m1"), amount: parseInt(deskGet("m1a")) || 1 }]; if (deskGet("m2")) materials.push({ id: deskGet("m2"), amount: parseInt(deskGet("m2a")) || 1 }); c.rewards = { pages: parseInt(deskGet("pages")) || 0, levels: parseInt(deskGet("levels")) || 0, materials: materials, artifact: deskGet("art") || "" }; saveContent(); renderAll(); alert("Chapter updated."); }); }
function deskDeleteChapter() { ensureStory(); const vid = getSelectValue("deskVolSelect"); const cid = getSelectValue("deskChapSelect"); const v = content.story.volumes.find(x => x.id === vid); if (!v) { alert("No volume."); return; } if (!cid) { alert("No chapter."); return; } if (!confirm("Delete chapter?")) return; v.chapters = v.chapters.filter(c => c.id !== cid); saveContent(); renderAll(); alert("Chapter deleted."); }
function deskEditBattleLines() { const id = getSelectValue("deskCharSelect"); if (!id) { alert("No character selected."); return; } const c = content.characters.find(x => x.id === id); if (!c) return; const cur = getCharLines(id, "battle"); const fields = []; for (let i = 0; i < 5; i++) fields.push({ id: "b" + i, label: "Battle line " + (i + 1), value: cur[i] || "" }); deskOpenForm("Battle Lines: " + c.name, fields, function () { const lines = []; for (let i = 0; i < 5; i++) { const t = deskGet("b" + i); if (t) lines.push(t); } content.char_lines[id].battle = lines; saveContent(); renderAll(); alert("Battle lines saved."); }); }
const __rr2 = renderAll;
function renderAll() { __rr2(); renderDeskStory(); }
(function () { if (document.getElementById("deskStoryVol")) return; const desk = document.getElementById("tab-desk"); const w = document.createElement("div"); w.innerHTML = "<h3>Story Mode</h3><div id='deskStoryVol'></div><button onclick='deskAddVolume()'>Add Volume</button><button onclick='deskDeleteVolume()'>Delete Volume</button><div id='deskStoryChap'></div><button onclick='deskAddChapter()'>Add Chapter</button><button onclick='deskEditChapter()'>Edit Chapter</button><button onclick='deskDeleteChapter()'>Delete Chapter</button>"; desk.appendChild(w); })();
(function () { if (document.getElementById("battleLinesBtn")) return; const charBox = document.getElementById("deskCharacters"); if (!charBox) return; const b = document.createElement("button"); b.id = "battleLinesBtn"; b.innerText = "Edit Battle Lines"; b.onclick = deskEditBattleLines; charBox.parentNode.insertBefore(b, charBox.nextSibling); })();
