let deskFormCallback = null;
function deskFormContainer() { let el = document.getElementById("deskForm"); if (!el) { el = document.createElement("div"); el.id = "deskForm"; const desk = document.getElementById("tab-desk"); desk.insertBefore(el, desk.children[1] || null); } return el; }
function deskOpenForm(title, fields, onSave) { deskFormCallback = onSave; let h = "<div class='card'><strong>" + title + "</strong>"; for (const f of fields) { h += "<div class='small'>" + f.label + "</div><input id='df_" + f.id + "' type='text' value=\"" + String(f.value == null ? "" : f.value).replace(/"/g, "&quot;") + "\">"; } h += "<button onclick=\"deskSaveForm()\">Save</button><button onclick=\"deskCloseForm()\">Cancel</button></div>"; deskFormContainer().innerHTML = h; deskFormContainer().scrollIntoView({ behavior: "smooth", block: "center" }); }
function deskGet(id) { const el = document.getElementById("df_" + id); return el ? el.value : ""; }
function deskSaveForm() { const cb = deskFormCallback; if (cb) cb(); deskCloseForm(); }
function deskCloseForm() { deskFormCallback = null; deskFormContainer().innerHTML = ""; }

function deskAddMedia() { deskOpenForm("Add Media", [ { id: "label", label: "Label (e.g. Luna portrait)" }, { id: "path", label: "File name or https link (e.g. luna.png)" } ], function () { const label = deskGet("label"); const path = deskGet("path"); if (!label || !path) { alert("Fill both fields."); return; } content.media.push({ id: slugId(label) + "_" + (Date.now() % 1000), label: label, path: path }); saveContent(); renderAll(); alert("Media added."); }); }

function deskEditBanner() { const id = getSelectValue("deskBannerSelect"); if (!id) { alert("No banner selected."); return; } const b = content.banners.find(x => x.id === id); if (!b) return; deskOpenForm("Edit Banner", [ { id: "name", label: "Name", value: b.name }, { id: "featured", label: "Featured character ids", value: b.featured.join(", ") }, { id: "start", label: "Start (limited only)", value: b.availability ? b.availability.start : "" }, { id: "end", label: "End (limited only)", value: b.availability ? b.availability.end : "" } ], function () { b.name = deskGet("name") || b.name; b.featured = commaList(deskGet("featured")); if (b.availability && b.availability.type === "limited") { b.availability.start = deskGet("start") || b.availability.start; b.availability.end = deskGet("end") || b.availability.end; } saveContent(); renderAll(); alert("Banner updated."); }); }

function deskAddCharacter() { deskOpenForm("Add Character", [ { id: "name", label: "Name" }, { id: "rarity", label: "Rarity (3,4,5)", value: "5" }, { id: "element", label: "Element", value: "moon" }, { id: "cls", label: "Class", value: "mage" }, { id: "hp", label: "Base HP", value: "800" }, { id: "atk", label: "Base ATK", value: "120" }, { id: "def", label: "Base DEF", value: "70" }, { id: "growth", label: "Growth (HP,ATK,DEF)", value: "60,10,5" }, { id: "fav", label: "Favorite tags", value: "sweet" }, { id: "hated", label: "Hated tags", value: "spicy" } ], function () { const name = deskGet("name"); if (!name) { alert("Name required."); return; } let id = slugId(name); if (content.characters.some(c => c.id === id)) id = id + "_" + (Date.now() % 1000); const growth = commaList(deskGet("growth")).map(n => parseInt(n) || 0); content.characters.push({ id: id, name: name, rarity: parseInt(deskGet("rarity")) || 5, element: deskGet("element") || "moon", class: deskGet("cls") || "mage", favorite_tags: commaList(deskGet("fav")), hated_tags: commaList(deskGet("hated")), stats: { hp: parseInt(deskGet("hp")) || 800, atk: parseInt(deskGet("atk")) || 120, def: parseInt(deskGet("def")) || 70 }, growth: { hp: growth[0] || 0, atk: growth[1] || 0, def: growth[2] || 0 }, images: { portrait: "", card: "" } }); saveContent(); renderAll(); alert("Character added: " + name); }); }

function deskEditCharacter() { const id = getSelectValue("deskCharSelect"); if (!id) { alert("No character selected."); return; } const c = content.characters.find(x => x.id === id); if (!c) return; deskOpenForm("Edit Character", [ { id: "name", label: "Name", value: c.name }, { id: "rarity", label: "Rarity (3,4,5)", value: c.rarity }, { id: "element", label: "Element", value: c.element }, { id: "cls", label: "Class", value: c.class }, { id: "hp", label: "Base HP", value: c.stats.hp }, { id: "atk", label: "Base ATK", value: c.stats.atk }, { id: "def", label: "Base DEF", value: c.stats.def }, { id: "fav", label: "Favorite tags", value: c.favorite_tags.join(", ") }, { id: "hated", label: "Hated tags", value: c.hated_tags.join(", ") } ], function () { c.name = deskGet("name") || c.name; c.rarity = parseInt(deskGet("rarity")) || c.rarity; c.element = deskGet("element") || c.element; c.class = deskGet("cls") || c.class; c.stats.hp = parseInt(deskGet("hp")) || c.stats.hp; c.stats.atk = parseInt(deskGet("atk")) || c.stats.atk; c.stats.def = parseInt(deskGet("def")) || c.stats.def; c.favorite_tags = commaList(deskGet("fav")); c.hated_tags = commaList(deskGet("hated")); saveContent(); renderAll(); alert("Character updated."); }); }
// END FORMS PART 1
function deskAddRelationship() { deskOpenForm("Add Bond / Couple", [ { id: "m1", label: "Member 1 id" }, { id: "m2", label: "Member 2 id" }, { id: "name", label: "Bond name", value: "Bound Hearts" }, { id: "type", label: "Type (couple,friend,rival)", value: "couple" }, { id: "stat", label: "Buff stat (hp,atk,def)", value: "atk" }, { id: "value", label: "Buff percent", value: "15" } ], function () { const m1 = deskGet("m1"); const m2 = deskGet("m2"); if (!m1 || !m2) { alert("Both members required."); return; } if (!content.characters.some(c => c.id === m1) || !content.characters.some(c => c.id === m2)) { alert("Member not found."); return; } const name = deskGet("name") || "Bound Hearts"; const stat = deskGet("stat") || "atk"; const value = parseInt(deskGet("value")) || 15; content.relationships.push({ id: m1 + "_" + m2 + "_" + (deskGet("type") || "couple"), name: name, type: deskGet("type") || "couple", members: [m1, m2], enabled: true, team_buff: { name: name, description: getCharacterName(m1) + " & " + getCharacterName(m2) + " together: " + stat.toUpperCase() + " +" + value + "%.", effects: [{ type: "stat_percent", stat: stat, value: value }] } }); saveContent(); renderAll(); alert("Relationship added."); }); }

function deskEditRelationship() { const id = getSelectValue("deskRelSelect"); if (!id) { alert("No relationship selected."); return; } const r = content.relationships.find(x => x.id === id); if (!r) return; const eff = r.team_buff.effects[0] || { stat: "atk", value: 15 }; deskOpenForm("Edit Relationship", [ { id: "name", label: "Bond name", value: r.name }, { id: "type", label: "Type", value: r.type }, { id: "stat", label: "Buff stat", value: eff.stat }, { id: "value", label: "Buff percent", value: eff.value } ], function () { r.name = deskGet("name") || r.name; r.type = deskGet("type") || r.type; let e = r.team_buff.effects[0] || { type: "stat_percent" }; e.stat = deskGet("stat") || e.stat; e.value = parseInt(deskGet("value")) || e.value; r.team_buff.effects = [e]; r.team_buff.name = r.name; r.team_buff.description = r.members.map(getCharacterName).join(" & ") + " together: " + e.stat.toUpperCase() + " +" + e.value + "%."; saveContent(); renderAll(); alert("Relationship updated."); }); }

function deskAddRefreshment() { deskOpenForm("Add Refreshment", [ { id: "name", label: "Name" }, { id: "rarity", label: "Rarity (3,4,5)", value: "3" }, { id: "tags", label: "Tags", value: "spicy" }, { id: "fav", label: "Favorite line", value: "I love this food!" }, { id: "neu", label: "Neutral line", value: "It is okay." }, { id: "hat", label: "Hated line", value: "I hate this food!" } ], function () { const name = deskGet("name"); if (!name) { alert("Name required."); return; } let id = slugId(name); if (content.refreshments.some(f => f.id === id)) id = id + "_" + (Date.now() % 1000); content.refreshments.push({ id: id, name: name, rarity: parseInt(deskGet("rarity")) || 3, tags: commaList(deskGet("tags")), images: { icon: "" }, reactions: { favorite: [deskGet("fav")], neutral: [deskGet("neu")], hated: [deskGet("hat")] } }); saveContent(); renderAll(); alert("Refreshment added: " + name); }); }

function deskEditRefreshment() { const id = getSelectValue("deskFoodSelect"); if (!id) { alert("No refreshment selected."); return; } const f = content.refreshments.find(x => x.id === id); if (!f) return; deskOpenForm("Edit Refreshment", [ { id: "name", label: "Name", value: f.name }, { id: "rarity", label: "Rarity (3,4,5)", value: f.rarity }, { id: "tags", label: "Tags", value: f.tags.join(", ") }, { id: "fav", label: "Favorite line", value: f.reactions.favorite[0] }, { id: "neu", label: "Neutral line", value: f.reactions.neutral[0] }, { id: "hat", label: "Hated line", value: f.reactions.hated[0] } ], function () { f.name = deskGet("name") || f.name; f.rarity = parseInt(deskGet("rarity")) || f.rarity; f.tags = commaList(deskGet("tags")); f.reactions.favorite = [deskGet("fav")]; f.reactions.neutral = [deskGet("neu")]; f.reactions.hated = [deskGet("hat")]; saveContent(); renderAll(); alert("Refreshment updated."); }); }

function deskAddExpedition() { deskOpenForm("Add Expedition", [ { id: "name", label: "Name" }, { id: "candlelight", label: "Candlelight cost", value: "10" }, { id: "duration", label: "Duration minutes", value: "30" }, { id: "power", label: "Recommended power", value: "3000" }, { id: "pages", label: "Pages reward", value: "200" }, { id: "shards", label: "Shards reward", value: "40" }, { id: "dust", label: "Vellum Dust", value: "3" }, { id: "embers", label: "Lumina Embers", value: "0" } ], function () { const name = deskGet("name"); if (!name) { alert("Name required."); return; } let id = slugId(name); if (content.expeditions.some(e => e.id === id)) id = id + "_" + (Date.now() % 1000); const rewards = []; const pages = parseInt(deskGet("pages")) || 0; const shards = parseInt(deskGet("shards")) || 0; const dust = parseInt(deskGet("dust")) || 0; const embers = parseInt(deskGet("embers")) || 0; if (pages) rewards.push({ type: "currency", id: "chronicle_pages", amount: pages }); if (shards) rewards.push({ type: "currency", id: "inkwell_shards", amount: shards }); if (dust) rewards.push({ type: "material", id: "vellum_dust", amount: dust }); if (embers) rewards.push({ type: "material", id: "lumina_embers", amount: embers }); content.expeditions.push({ id: id, name: name, candlelight: parseInt(deskGet("candlelight")) || 10, duration_minutes: parseInt(deskGet("duration")) || 30, recommended_power: parseInt(deskGet("power")) || 3000, rewards: rewards }); saveContent(); renderAll(); alert("Expedition added: " + name); }); }

function deskEditExpedition() { const id = getSelectValue("deskExpSelect"); if (!id) { alert("No expedition selected."); return; } const e = content.expeditions.find(x => x.id === id); if (!e) return; deskOpenForm("Edit Expedition", [ { id: "name", label: "Name", value: e.name }, { id: "candlelight", label: "Candlelight cost", value: e.candlelight }, { id: "duration", label: "Duration minutes", value: e.duration_minutes }, { id: "power", label: "Recommended power", value: e.recommended_power }, { id: "pages", label: "Pages reward", value: getRewardAmount(e, "currency", "chronicle_pages") }, { id: "shards", label: "Shards reward", value: getRewardAmount(e, "currency", "inkwell_shards") }, { id: "dust", label: "Vellum Dust", value: getRewardAmount(e, "material", "vellum_dust") }, { id: "embers", label: "Lumina Embers", value: getRewardAmount(e, "material", "lumina_embers") } ], function () { e.name = deskGet("name") || e.name; e.candlelight = parseInt(deskGet("candlelight")) || e.candlelight; e.duration_minutes = parseInt(deskGet("duration")) || e.duration_minutes; e.recommended_power = parseInt(deskGet("power")) || e.recommended_power; const rewards = []; const pages = parseInt(deskGet("pages")) || 0; const shards = parseInt(deskGet("shards")) || 0; const dust = parseInt(deskGet("dust")) || 0; const embers = parseInt(deskGet("embers")) || 0; if (pages) rewards.push({ type: "currency", id: "chronicle_pages", amount: pages }); if (shards) rewards.push({ type: "currency", id: "inkwell_shards", amount: shards }); if (dust) rewards.push({ type: "material", id: "vellum_dust", amount: dust }); if (embers) rewards.push({ type: "material", id: "lumina_embers", amount: embers }); e.rewards = rewards; saveContent(); renderAll(); alert("Expedition updated."); }); }
// END FORMS PART 2

